# Generated by Django 4.2 on 2023-04-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'street',
                'verbose_name_plural': 'streets',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('building', models.PositiveIntegerField(verbose_name='building')),
                ('opening_time', models.TimeField(verbose_name='opening_time')),
                ('closing_time', models.TimeField(verbose_name='closing_time')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.city', verbose_name='city')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.street', verbose_name='street')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
    ]
