# Generated by Django 4.2 on 2023-04-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('name', 'city', 'street', 'building')},
        ),
    ]
